Models/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(4096,MinimumLength = 10)]
        public string Message { get; set; }
    }
}

Models/ViewModels/TripViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class TripViewModel
    {
        public string Name { get; set; }
        public DateTimeOffset DateCreated { get; set; }
    }
        
}

Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheWorld.Models;
using TheWorld.Services;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TheWorld.Controllers
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;
        private IWorldRepository _repository;

        public AppController(IMailService mailService, IConfigurationRoot config, IWorldRepository repository)
        {
            _mailService = mailService;
            _config = config;
            _repository = repository;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Trips()
        {
            var data = _repository.GetTripsByUsername(this.User.Identity.Name);

            return View(data);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (model.Email.EndsWith("blacklisted.com")) {
                ModelState.AddModelError("","This email is blacklisted.");
            }

            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "The World", model.Message);
            }

            ModelState.Clear();

            ViewBag.UserMessage = "Message Sent";

            return View();
        }
    }
}

Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheWorld.Models;
using AutoMapper;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

namespace TheWorld.Controllers
{
    [Authorize]
    [Produces("application/json")]
    [Route("api/Trips")]
    public class TripsController : Controller
    {
        private readonly WorldContext _context;
        private ILogger<TripsController> _logger;

        public TripsController(WorldContext context, ILogger<TripsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: api/Trips
        [HttpGet]
        public IEnumerable<Trip> GetTrips()
        {
            var trips = Mapper.Map<IEnumerable<Trip>>(_context.Trips);
            return trips;
        }

        // GET: api/Trips/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetTrip([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            

            if (trip == null)
            {
                return NotFound();
            }

            return Ok(trip);
        }

        // PUT: api/Trips/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTrip([FromRoute] int id, [FromBody] Trip trip)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != trip.Id)
            {
                return BadRequest();
            }

            _context.Entry(trip).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TripExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Trips
        [HttpPost]
        public async Task<IActionResult> PostTrip([FromBody] TripViewModel tripViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // convert TripViewModel to Trip
            var trip = Mapper.Map<Trip>(tripViewModel);

            trip.UserName = User.Identity.Name;

            //_logger.LogError();
            _logger.LogInformation($"Trip: {trip} ");

            _context.Trips.Add(trip);

            await _context.SaveChangesAsync();

            return CreatedAtAction("GetTrip", new { id = trip.Id }, trip);
        }

        // DELETE: api/Trips/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteTrip([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var trip = await _context.Trips.SingleOrDefaultAsync(m => m.Id == id);
            if (trip == null)
            {
                return NotFound();
            }

            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();

            return Ok(trip);
        }

        private bool TripExists(int id)
        {
            return _context.Trips.Any(e => e.Id == id);
        }
    }
}

Views/App/About.cshtml
@{
    ViewBag.title = "About";
}
<h1>About</h1>

Views/App/Contact.cshtml
@model TheWorld.Models.ContactViewModel
@{
    ViewBag.title = "Contact";
}
@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Contact</h2>
        <form method="post">
            <span asp-validation-summary="ModelOnly"></span>
            @if (ViewBag.UserMessage != null)
            {
                <div>@ViewBag.UserMessage</div>
            }
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"  class="text-muted"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" type="email" class="form-control" />
                <span asp-validation-for="Email"  class="text-muted"></span>
                </div>
            <div class="form-group">
                <label asp-for="Message">Message</label>
                <textarea cols="40" rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-success" />
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>
</div>

Views/App/Index.cshtml
@{ 
    ViewBag.title = "Home Page";
}

<div class="row">
    <div class="col-md-6">
        <h1>Welcome to The World</h1>
        <p>Plan for your world trips</p>
        <div class="form-group">
            <a asp-controller="App" asp-action="Trips" class="btn btn-lg btn-success" >View My Trips</a>
        </div>
    </div>
</div>

Views/App/Trips.cshtml
@model IEnumerable<TheWorld.Models.Trip>
@{ 
    ViewBag.title = "Home Page";
}

<div class="row">
    <div class="col-md-6">
        <h1>The World</h1>
        <p>This will be a fun site soon!</p>

        <form>
            <div class="form-group">
                <label>Date</label>
                <input class="form-control" />
            </div>
            <div class="form-group">
                <label>Location</label>
                <input class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="add" class="btn btn-success" />
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <h1>Map</h1>
        <ul>
            @foreach (var item in Model)
            {
                <li>@item.Name @item.DateCreated.ToString("D")</li>
            }
        </ul>
    </div>
</div>